// Generated by gencpp from file arbotix_msgs/Relax.msg
// DO NOT EDIT!


#ifndef ARBOTIX_MSGS_MESSAGE_RELAX_H
#define ARBOTIX_MSGS_MESSAGE_RELAX_H

#include <ros/service_traits.h>


#include <arbotix_msgs/RelaxRequest.h>
#include <arbotix_msgs/RelaxResponse.h>


namespace arbotix_msgs
{

struct Relax
{

typedef RelaxRequest Request;
typedef RelaxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Relax
} // namespace arbotix_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arbotix_msgs::Relax > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::arbotix_msgs::Relax&) { return value(); }
};

template<>
struct DataType< ::arbotix_msgs::Relax > {
  static const char* value()
  {
    return "arbotix_msgs/Relax";
  }

  static const char* value(const ::arbotix_msgs::Relax&) { return value(); }
};


// service_traits::MD5Sum< ::arbotix_msgs::RelaxRequest> should match 
// service_traits::MD5Sum< ::arbotix_msgs::Relax > 
template<>
struct MD5Sum< ::arbotix_msgs::RelaxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arbotix_msgs::Relax >::value();
  }
  static const char* value(const ::arbotix_msgs::RelaxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arbotix_msgs::RelaxRequest> should match 
// service_traits::DataType< ::arbotix_msgs::Relax > 
template<>
struct DataType< ::arbotix_msgs::RelaxRequest>
{
  static const char* value()
  {
    return DataType< ::arbotix_msgs::Relax >::value();
  }
  static const char* value(const ::arbotix_msgs::RelaxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arbotix_msgs::RelaxResponse> should match 
// service_traits::MD5Sum< ::arbotix_msgs::Relax > 
template<>
struct MD5Sum< ::arbotix_msgs::RelaxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arbotix_msgs::Relax >::value();
  }
  static const char* value(const ::arbotix_msgs::RelaxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arbotix_msgs::RelaxResponse> should match 
// service_traits::DataType< ::arbotix_msgs::Relax > 
template<>
struct DataType< ::arbotix_msgs::RelaxResponse>
{
  static const char* value()
  {
    return DataType< ::arbotix_msgs::Relax >::value();
  }
  static const char* value(const ::arbotix_msgs::RelaxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARBOTIX_MSGS_MESSAGE_RELAX_H
