// Generated by gencpp from file communicate/AddTwoInts.msg
// DO NOT EDIT!


#ifndef COMMUNICATE_MESSAGE_ADDTWOINTS_H
#define COMMUNICATE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <communicate/AddTwoIntsRequest.h>
#include <communicate/AddTwoIntsResponse.h>


namespace communicate
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace communicate


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::communicate::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::communicate::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::communicate::AddTwoInts > {
  static const char* value()
  {
    return "communicate/AddTwoInts";
  }

  static const char* value(const ::communicate::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::communicate::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::communicate::AddTwoInts > 
template<>
struct MD5Sum< ::communicate::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::communicate::AddTwoInts >::value();
  }
  static const char* value(const ::communicate::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::communicate::AddTwoIntsRequest> should match 
// service_traits::DataType< ::communicate::AddTwoInts > 
template<>
struct DataType< ::communicate::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::communicate::AddTwoInts >::value();
  }
  static const char* value(const ::communicate::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::communicate::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::communicate::AddTwoInts > 
template<>
struct MD5Sum< ::communicate::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::communicate::AddTwoInts >::value();
  }
  static const char* value(const ::communicate::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::communicate::AddTwoIntsResponse> should match 
// service_traits::DataType< ::communicate::AddTwoInts > 
template<>
struct DataType< ::communicate::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::communicate::AddTwoInts >::value();
  }
  static const char* value(const ::communicate::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMUNICATE_MESSAGE_ADDTWOINTS_H
