// Generated by gencpp from file communicate/Person.msg
// DO NOT EDIT!


#ifndef COMMUNICATE_MESSAGE_PERSON_H
#define COMMUNICATE_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communicate
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : name()
    , sex(0)
    , age(0)  {
    }
  Person_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , sex(0)
    , age(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _sex_type;
  _sex_type sex;

   typedef uint8_t _age_type;
  _age_type age;



  enum {
    unkonwn = 0u,
    male = 1u,
    female = 2u,
  };


  typedef boost::shared_ptr< ::communicate::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communicate::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::communicate::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::communicate::Person > PersonPtr;
typedef boost::shared_ptr< ::communicate::Person const> PersonConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communicate::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communicate::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace communicate

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'communicate': ['/home/wpr/code/VSLAM/ROS/ROS\xe5\x9f\xba\xe7\xa1\x80/learningcommunicate/src/communicate/msg', '/home/wpr/code/VSLAM/ROS/ROS\xe5\x9f\xba\xe7\xa1\x80/learningcommunicate/devel/share/communicate/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::communicate::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communicate::Person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communicate::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communicate::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communicate::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communicate::Person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communicate::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6c586fe5db3b6c5bf0caaabb580d8d9";
  }

  static const char* value(const ::communicate::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6c586fe5db3b6c5ULL;
  static const uint64_t static_value2 = 0xbf0caaabb580d8d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::communicate::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communicate/Person";
  }

  static const char* value(const ::communicate::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communicate::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
uint8 sex\n\
uint8 age\n\
\n\
uint8 unkonwn = 0\n\
uint8 male = 1\n\
uint8 female = 2\n\
";
  }

  static const char* value(const ::communicate::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communicate::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.sex);
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communicate::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communicate::Person_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "sex: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sex);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATE_MESSAGE_PERSON_H
