// Generated by gencpp from file arbotix_msgs/SetupChannel.msg
// DO NOT EDIT!


#ifndef ARBOTIX_MSGS_MESSAGE_SETUPCHANNEL_H
#define ARBOTIX_MSGS_MESSAGE_SETUPCHANNEL_H

#include <ros/service_traits.h>


#include <arbotix_msgs/SetupChannelRequest.h>
#include <arbotix_msgs/SetupChannelResponse.h>


namespace arbotix_msgs
{

struct SetupChannel
{

typedef SetupChannelRequest Request;
typedef SetupChannelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetupChannel
} // namespace arbotix_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arbotix_msgs::SetupChannel > {
  static const char* value()
  {
    return "c65e58d8b3b4d406126f6dc829a6011f";
  }

  static const char* value(const ::arbotix_msgs::SetupChannel&) { return value(); }
};

template<>
struct DataType< ::arbotix_msgs::SetupChannel > {
  static const char* value()
  {
    return "arbotix_msgs/SetupChannel";
  }

  static const char* value(const ::arbotix_msgs::SetupChannel&) { return value(); }
};


// service_traits::MD5Sum< ::arbotix_msgs::SetupChannelRequest> should match 
// service_traits::MD5Sum< ::arbotix_msgs::SetupChannel > 
template<>
struct MD5Sum< ::arbotix_msgs::SetupChannelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arbotix_msgs::SetupChannel >::value();
  }
  static const char* value(const ::arbotix_msgs::SetupChannelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arbotix_msgs::SetupChannelRequest> should match 
// service_traits::DataType< ::arbotix_msgs::SetupChannel > 
template<>
struct DataType< ::arbotix_msgs::SetupChannelRequest>
{
  static const char* value()
  {
    return DataType< ::arbotix_msgs::SetupChannel >::value();
  }
  static const char* value(const ::arbotix_msgs::SetupChannelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arbotix_msgs::SetupChannelResponse> should match 
// service_traits::MD5Sum< ::arbotix_msgs::SetupChannel > 
template<>
struct MD5Sum< ::arbotix_msgs::SetupChannelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arbotix_msgs::SetupChannel >::value();
  }
  static const char* value(const ::arbotix_msgs::SetupChannelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arbotix_msgs::SetupChannelResponse> should match 
// service_traits::DataType< ::arbotix_msgs::SetupChannel > 
template<>
struct DataType< ::arbotix_msgs::SetupChannelResponse>
{
  static const char* value()
  {
    return DataType< ::arbotix_msgs::SetupChannel >::value();
  }
  static const char* value(const ::arbotix_msgs::SetupChannelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARBOTIX_MSGS_MESSAGE_SETUPCHANNEL_H
